title: Kennedy Kyalo
email: kennedykyalo168@gmail.com
logo: assets/img/about.png
show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
minima:
  skin: dark

markdown: kramdown

url: "https://ken-warren.github.io/"
baseurl: "solar_battery-investment/"
gem "github-pages", group: :jekyll_plugins

github_username: ken-warren
